### ISSUE TITLE
Applications module don't load python dependency module

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/spack#214]
```
module load spykfunc
module list
```
This is missing python! Without loading the python module, Spykfunc will fail on the cluster, since different version of python will be used by the master and worker processes.

**Comment by pramodk** [comment]
I assume this is because we don't generate module in `application` level and then chain doesn't auto-load dependencies module from upstream chains?

If so, I wonder if we should ping Peter about this. (Or, if you have idea already about this)

**Comment by matz-e** [comment]
I think if we add the module declaration for python to `packages.yaml`, it may generate it. I'll test next week.

**Comment by matz-e** [comment]
Fixed in #236.
