### ISSUE TITLE
Bash prompt disappears after loading module intel/18.0.3

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/spack#263]
I tried on BB5 to load the module `intel/18.0.3` after loading the pre-installed modules using `. /gpfs/bbp.cscs.ch/apps/hpc/jenkins/config/modules.sh`. After the module is loaded the bash prompt disappears but bash keeps being responsive. The same issue does not happen when loading other modules.

### Steps to reproduce the issue

```console
-bash-4.2$ . /gpfs/bbp.cscs.ch/apps/hpc/jenkins/config/modules.sh
-bash-4.2$ module load intel/18.0.3
ls
(works correctly, no bash prompt)
...
```

### Information on your system

`.bash_profile` only runs the script to setup spack env variables, the script to load the pre-installed modules and `module use -a "local_path"` to load the locally installed modules. The issue is present even if only the pre-installed modules are loaded and nothing is run from `.bash_profile`.

**Comment by matz-e** [comment]
Debug workflow:

    $ module show intel/18.0.3
    …random output…
    unsetenv	 PS1
    …more random output…

**Comment by alkino** [comment]
I think we can close it. I cannot reproduce.

**Comment by iomaganaris** [comment]
Yes, I think it works fine now :+1:
