### ISSUE TITLE
Add emacs module to tools on BB5

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/spack#274]
Here is request from CS : 

```
We have a user requesting emacs on BB5 (https://bbpteam.epfl.ch/project/issues/browse/HELP-10166), 
and it seems that emacs 26 is available in Spack…
Would it be possible to install it in tools?
```
@st4rl3ss  : a basic example to understand workflow of module deployment with Spack on BB5.

Things to check : 

* Use spack chanin on BB5 : https://github.com/BlueBrain/spack#building-software-with-spack-at-bluebrain
* Check on BB5 if you can install module locally
* Add package to tools section in : https://github.com/BlueBrain/spack/tree/develop/deploy/packages
* Enable module in tools: https://github.com/BlueBrain/spack/tree/develop/deploy/configs/tools
* File PR and check if Jenkins is build emacs
* Use module from PR and test it on BB5
* Then merge PR

Matthias can help you with this.

**Comment by st4rl3ss** [comment]
Emacs added to deployment in PR #277.
