### ISSUE TITLE
Module not found when using `spack load`

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/spack#294]
I want to use `clang-format-7` inside a `build-env` for project zee. So inside a build-env I ran `spack load llvm@7.0.0`, but then it failed to find the module `llvm-7.0.0-gcc-6.4.0-u4xegyz`

### Steps to reproduce the issue

```console
bb5$ . /gpfs/bbp.cscs.ch/apps/hpc/jenkins/config/modules.sh
bb5$ spack build-env zee@develop bash
build-env$ spack load llvm@7.0.0
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'llvm-7.0.0-gcc-6.4.0-u4xegyz'
```

It should load module `llvm/7.0.0` instead.

**Comment by matz-e** [comment]
Why don't you use `module load`?

**Comment by tristan0x** [comment]
> Why don't you use `module load`?

This is what I am using instead indeed. But this is a workaround. `spack load` should work

**Comment by matz-e** [comment]
Do you have a `modules.yaml` configuration to tell Spack how to deal with modules?

**Comment by tristan0x** [comment]
No. Should I use `/gpfs/bbp.cscs.ch/apps/hpc/jenkins/config/modules.sh`?

**Comment by matz-e** [comment]
We don't currently support an end-user facing `modules.yaml`. [You can use this one in the meantime](https://github.com/BlueBrain/spack/blob/develop/deploy/configs/applications/modules.yaml)

**Comment by tristan0x** [comment]
> We don't currently support an end-user facing `modules.yaml`. [You can use this one in the meantime](https://github.com/BlueBrain/spack/blob/develop/deploy/configs/applications/modules.yaml)

Thank you @matz-e 
Error is now different:

```
[tcarel@bbpv2 ~]$ spack load llvm@7.0.0   
==> Error: Even though llvm@7.0.0%gcc@6.4.0+all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb+polly~python~shared_libs arch=linux-rhel7-x86_64  ^libedit@3.1-20170329%gcc@6.4.0 rch=linux-rhel7-x86_64  ^py-lit@0.5.0%gcc@6.4.0 arch=linux-rhel7-x86_64  ^swig@3.0.12%gcc@6.4.0 arch=linux-rhel7-x86_64 is installed, no tcl module has been generated for it.
```

**Comment by matz-e** [comment]
Hmm. `llvm` is probably not in the whitelist of that `modules.yaml`. I'll add it to my list to create a holistic `modules.yaml`.

**Comment by tristan0x** [comment]
Error changed

```
$ spack load llvm@7.0.0  
==> Error: Even though llvm@7.0.0%gcc@6.4.0+all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb+polly~python~shared_libs arch=linux-rhel7-x86_64  ^libedit@3.1-20170329%gcc@6.4.0 arch=linux-rhel7-x86_64  ^py-lit@0.5.0%gcc@6.4.0 arch=linux-rhel7-x86_64  ^swig@3.0.12%gcc@6.4.0 arch=linux-rhel7-x86_64 is installed, no tcl module has been generated for it.
```

I have the same issue with Jenkins `modules.sh` file sourced.

**Comment by tristan0x** [comment]
> Error changed
> 

Actually, it didn't change since 8 days ago... sorry...
Any news about it?

**Comment by matz-e** [comment]
missing `modules.yaml`. Use `module load`, as discussed before :)

**Comment by tristan0x** [comment]
> Hmm. `llvm` is probably not in the whitelist of that `modules.yaml`. I'll add it to my list to create a holistic `modules.yaml`.

What about that? Do you want me to create a dedicated issue and close this one?

**Comment by matz-e** [comment]
https://bbpteam.epfl.ch/project/issues/browse/HPCTM-1210

**Comment by matz-e** [comment]
We put stuff like that into JIRA :)

**Comment by tristan0x** [comment]
> https://bbpteam.epfl.ch/project/issues/browse/HPCTM-1210

Thank you @matz-e
