### ISSUE TITLE
spack setup creates default empty files

### ISSUE THREAD

**Issue by jorblancoa** [BlueBrain/spack#342]
The "spack setup" command creates default empty files with the name of the project on the lib/, bin/ and include/ folders.

In BB5, the make install command will copy the libraries on lib64/ instead of lib/, causing some packages to export the wrong empty generated library.

i.e. Reporting lib recipe:
```
@property
def libs(self):
...
    search_paths = [[self.prefix.lib, False], [self.prefix.lib64, False]]
...
```
The empty library on the lib/ directory will be found and returned, causing the packages that depend on it to fail on the linking step.

### Steps to reproduce the issue

```console
$ spack setup reportinglib@develop
$ cd <PathToInstalledSoftware>/reportinglib-develop-xxxxx
$ ls -al bin/
-rwxr-xr-x 1 jblanco bbp-core    0 Apr 25 17:43 reportinglib
$ ls -al include/
-rwxr-xr-x 1 jblanco bbp-core    0 Apr 25 17:43 reportinglib.h
$ ls -al lib/
-rwxr-xr-x 1 jblanco bbp-core    0 Apr 25 17:43 libreportinglib.a
-rwxr-xr-x 1 jblanco bbp-core    0 Apr 25 17:43 libreportinglib.so
```

**Comment by jplanasc** [comment]
Found same issue with same library :)
I created a PR to prioritize looking into lib64 directory instead of lib, as per Pramod's request. The issue is still there, but the linking step for reportinglib should be solved with:
https://github.com/BlueBrain/spack/pull/480

**Comment by jorblancoa** [comment]
Duplicate from [BSD-4](https://bbpteam.epfl.ch/project/issues/browse/BSD-4)
