### ISSUE TITLE
py-bglibpy module is not loading full neuron

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/spack#344]
For some reason on BB5 the py-bglibpy module is not loading a full neuron install.
E.g. the 'nrnivmodl' command is not working after loading the module.

( @romani79, the next blocker for the minis )

**Comment by pramodk** [comment]
@wvangeit : do you mean when you load `py-bglibpy`, neuron module is not auto-loaded? I didn't get what you mean by `full neuron`.

**Comment by wvangeit** [comment]
With 'full neuron' I mean 'fully functional neuron'. 
As I mentioned, when I load the module on BB5 I don't have an 'nrnivmodl' command for example.
There is also no 'nrniv' etc.

**Comment by ferdonline** [comment]
Indeed the neuron module is not automatically loaded. In fact, none of the direct dependencies is automatically loaded. This might be a limitation of the PythonPackage builder.
@wvangeit for the moment could you manually do `module load neuron` while we look into this?

As a though, couldnt the dependency on neuron be dropped since it anyway comes from neurodamus?

**Comment by wvangeit** [comment]
Since the python dependencies were autoloading, I was assuming that the same was the case for the other dependencies.
I can for now load a separate neuron module. But you have to tell me which one. I hope it's the same neuron install as the one that is being used by the neuron python module ? Because from my experience running an nrnivmodl from a different neuron install than the python module can generate issues.

About "anyway comes from neurodamus", no I don't think that's a good idea for the moment. Neurodamus doesn't have to be hard dependency of bglibpy. 
(Btw, are you saying that atm neurodamus is automatically loading neuron as dependency. If that's the case I don't understand why this doesn't work for py-bglibpy)

Imo, all the dependencies should auto-load. This was one of the big annoyances of nix, one had to manually figure out which other modules need to be loaded.
I consider this extremely user-unfriendly. In general users shouldn't need to know which dependencies to load when loading a package.
Making it a hybrid with python modules doing it, and other packages not makes it even more confusing.

It's also related to testing. Imo when spack packages get deployed they should be tested automatically. These tests should be done on the module with all its dependencies, so that the user is sure that a particular load command is 'guaranteed' to work.

**Comment by pramodk** [comment]
> Btw, are you saying that atm neurodamus is automatically loading neuron as dependency. If that's the case I don't understand why this doesn't work for py-bglibpy

yes, exactly! we didn't get time to debug this yesterday. With python2/3, Intel/GCC, MPI/NO-MPI, we dont want to users to pick the modules manually. Will get back to you.

**Comment by ferdonline** [comment]
> Neurodamus doesn't have to be hard dependency of bglibpy.

Ok I was not aware of that.

> Imo, all the dependencies should auto-load

Spack will auto-load "run" dependencies. What I meant is that maybe PythonPackages don't do that (as they are modules to be imported?).

In the module hierarchy there's only the most recent versions. Choose among `neuron/2018-10/python3/serial` and `neuron/2018-10/python2/serial`

But does bglibpy include mod files? I'm interesting in knowing better what it does and how people typically use it to think about the different deployment possibilities.

**Comment by wvangeit** [comment]
>Spack will auto-load "run" dependencies.

Then why isn't neuron loading when loading py-bglibpy ?
https://github.com/BlueBrain/spack/blob/develop/var/spack/repos/builtin/packages/py-bglibpy/package.py#L19

No bglibpy doesn't include mod files. So people have two options, or they load the neurodamus module, or they get the mod files from somewhere and compile them with nrnivmodl

**Comment by ferdonline** [comment]
The problem relates to the fact that there isn't a module file for the neuron that was picked during build. Following up in #348

**Comment by wvangeit** [comment]
I guess this is also fixed now ?

**Comment by matz-e** [comment]
> I guess this is also fixed now ? (at least it looks like it)

If so, is it OK to close this issue now, then?
