### ISSUE TITLE
Hippocampus mod files not building with spack neuron module

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/spack#356]
I'm unable to compile the hippocampus mod files on BB5 using the spack neuron module.

Step to reproduce:
clone bbpcode.epfl.ch/sim/models/hippocampus
(and get submodules)
then 
```
module load  neuron/2018-10
nrnivmodl hippocampus/mod
```

error message (at end of compilation):
```
libtool: link: unable to infer tagged configuration
libtool: link: specify a tag with `--tag'
```

Am I doing something wrong ?

This is blocking @romani79 's minis validation

**Comment by pramodk** [comment]
@jorblancoa : you encountered this, right? Did #348 fixed this?

**Comment by wvangeit** [comment]
This is fixed I assume ?

**Comment by pramodk** [comment]
yes...newer hippocampus module now loads correct neuron version.
