### ISSUE TITLE
Neurodamus-hippocampus incompatible with py-bglibpy

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/spack#366]
It seems there is some incompatibility between (on BB5) between neurodamus-hippocampus/0.2 and py-bglibpy module (or more probably the neuron module loaded by the latter).
When one loads the neurodamus-hippocampus/0.2 module, and then the py-bglibpy module, and one loads neuron, one gets:
dlopen failed -
/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/applications/2018-12-19/linux-rhel7-x86_64/intel-18.0.3/neurodamus-hippocampus-0.2-cshhesqrgp/lib/libnrnmech.so: undefined symbol: __libm_exp_table_128

The same happens when I load neurodamus-hippocampus/0.2 and py-bglibpy  and manually compile the hippocampus mod files using 'nrnivmodl'

**Comment by pramodk** [comment]
> I wrote detailed response to this ticket yesterday evening which I dont see here. Most likely lost it due to internet connect.

**Comment by wvangeit** [comment]
So @pramodk, what was you reply ?

**Comment by pramodk** [comment]
It was due to mix of PYTHONPATH from GCC compiled NEURON but nrnivmodl from Intel compiled NEURON (summarised details here).

Anyway, #371 should fix all issues.

**Comment by ferdonline** [comment]
@wvangeit closing this issue for now. If you find any issue please reopen

**Comment by wvangeit** [comment]
This still doesn't work on bb6:
└──> module load neurodamus-hippocampus  py-bglibpy/4.0.17/python3
Autoloading reportinglib/2.5.1
Autoloading hpe-mpi/2.16
Autoloading python/3.6.5
Autoloading neuron/7.6.6/python3/parallel
Autoloading neuron/7.6.6/python3/serial

└──> python
Python 3.6.5 (default, Dec 19 2018, 05:00:45) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bglibpy
dlopen failed - 
/gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/applications/2018-12-19/linux-rhel7-x86_64/intel-18.0.3/neurodamus-hippocampus-0.2-oy5ezutpyx/lib/libnrnmech.so: undefined symbol: __libm_exp_table_128

**Comment by wvangeit** [comment]
Moved to JIRA BSD-7

**Comment by pramodk** [comment]
For future reference : https://groups.google.com/forum/#!topic/enzo-users/0cShERaFBnE

**Comment by pramodk** [comment]
This was because of the conflicting neuron installations : bglibpy bring gcc compiled neuron whereas neurodamus bring intel compiled neuron. If we load neurodamus after bglibly then PYTHONPATH is set for neuron%intel which is consistent with libnrnmech.so from neurodamus.
