### ISSUE TITLE
Continuous integration for spack modules on BB5

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/spack#376]
It seems several people are having problems with spack packages on BB5. Both regressions, or trivial things that don't work, like https://github.com/BlueBrain/spack/issues/366

Could I propose that we fairly urgently add some continuous integration tests to the spack module deployment (and which are run after the nightly deployment or maybe ideally in a staging area before the actual deployment). 

The main reasons are:
- to introduce some 'memory' so that once something fails and is fixed, we can add another test so that we don't have regressions.
- allowing developers of packages to implement some logic to test their software every time it is deployed (these are the people knowing best what to test)

I think at least @romani79 would be interested in this to test e.g. hippocampus sims.

**Comment by pramodk** [comment]
@iomaganaris has created Jenkins plan that we will be connecting with Spack deployment. Will try to get this done next week.

cc: @matz-e

**Comment by matz-e** [comment]
Just for reference (my opinions):

* We don't want to run all the tests all the time, this will take a lot of time for CI and the turnaround time will be increased *a lot*
* Nightly testing can run everything, we should maybe tighten the run-time window from 0-6 to something like 0-3 in the morning
* For PRs, we need a list and actions to run what is needed, and only that:
  * Spack package name -> CI plan
  * If package appears to be installed in PR -> run CI

**Comment by iomaganaris** [comment]
The `Jenkins` plan for checking the modules deployed in bb5 is now integrated to the Spack deployment pipeline. Currently it works only for spack deployed modules but in the future we will be addressing more features.
You find see a sample output of the `Neurodamus` checks [here](https://bbpcode.epfl.ch/ci/blue/organizations/jenkins/hpc.module-testing/detail/hpc.module-testing/145/pipeline/52).

**Comment by pramodk** [comment]
@wvangeit : @iomaganaris  has setup [this Jenkinsfile](https://bbpcode.epfl.ch/browse/code/hpc/jenkins-pipeline/tree/Jenkinsfile.modules?h=refs/heads/master). This now runs before every merge. 

It would be great if you could suggest more test for your pipeline.

**Comment by wvangeit** [comment]
For now I think this is ok. We can extend it based on problems people experience while loading the modules
