### ISSUE TITLE
Support for re-installation of certain packages (--override functionality)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/spack#378]
Sometime we want to re-install certain packages even if `spec` is not changed. For example, if we bug fixed install method (that doesn't change DAG hash) or update environmental variables in recipe.

**Comment by matz-e** [comment]
Can we move this to JIRA?

**Comment by pramodk** [comment]
> Can we move this to JIRA?
yeah good idea!

**Comment by ferdonline** [comment]
I kind of agree with @matz-e suggestion. We can add a new version tag for newer deployments. As such the user can always go back if something gets screwed. Now, the question is how he would go back...
Would it make sense to have stable deployments, and nightly (alpha) ones? Users could then choose which set they wanted, and it would be less problematic eventual glitches in the alpha releases...

**Comment by pramodk** [comment]
>  We can add a new version tag for newer deployments.

But this doesn't solve general problem, for example, we have open source softwares where we have same issues.

But, I am now more concniced that we have to separate nightly deployments (which is more a development snapshot) vs. stable monthly deployment.

**Comment by matz-e** [comment]
> > We can add a new version tag for newer deployments.
> 
> But this doesn't solve general problem, for example, we have open source softwares where we have same issues.
> 
> But, I am now more concniced that we have to separate nightly deployments (which is more a development snapshot) vs. stable monthly deployment.

Overwriting versions that have already been deployed is still dangerous. I'd rather we add a little `-1` etc to the version number à la Fedora, OpenBSD et al.

In general, splitting the deployment into a more stable monthly one and a rapid dev: That sounds like our old archiving problem? We can just have a slower running pipeline that deploys into a different directory once a month…
