### ISSUE TITLE
No BGLIBPY_MOD_LIBRARY_PATH in neurodamus-core

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/spack#396]
It looks like neurodamus-core on BB5 doesn't have a BGLIBPY_MOD_LIBRARY_PATH variable.

(Probably best to check if the other neurodamus module have it all set)

**Comment by ferdonline** [comment]
neurodamus-core doesnt include any model, so no mod compilation happens.
I'd suggest we discuss the use cases with Pramod

**Comment by wvangeit** [comment]
Ok, but yeah, the entire idea of the core was to have these kind of mod files compiled into it

**Comment by pramodk** [comment]
@wvangeit  : now we have:

```
$ module show neurodamus-core/2.4.1/python3

setenv  HOC_LIBRARY_PATH /gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/applications/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/neurodamus-core-2.4.1-2x5lnxr7iw/hoc
setenv  MOD_LIBRARY_PATH /gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/applications/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/neurodamus-core-2.4.1-2x5lnxr7iw/mod
setenv  NRNMECH_LIB_PATH /gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/applications/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/neurodamus-core-2.4.1-2x5lnxr7iw/x86_64/.libs/libnrnmech.so

```

So there is `NRNMECH_LIB_PATH`. Do you really mean `BGLIBPY_MOD_LIBRARY_PATH`?

**Comment by wvangeit** [comment]
Yes, we need BGLIBPY_MOD_LIBRARY_PATH

**Comment by wvangeit** [comment]
Moved to JIRA BSD-6
