### ISSUE TITLE
deployed py-bluepy module doesn't load libsonata correctly

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/spack#463]
This fails:
```
module purge
module load py-bluepy/0.13.5/python3/serial
python3 -c 'import libsonata'
```
Resolved module is:
```
ls -al /gpfs/bbp.cscs.ch/apps/hpc/jenkins//modules/applications/2019-07/tcl/linux-rhel7-x86_64/py-bluepy/0.13.5/python3/serial
[...] Jul 30 05:30 [...]
```

It contains:
```
[...]
prepend-path     PYTHONPATH /gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/applications/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/py-libsonata-0.1.0-bauqh4b2nz/lib/python3.6/site-packages
[...]
```

But that path doesn't exist:
```
ls -al /gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/applications/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/py-libsonata-0.1.0-bauqh4b2nz/lib/python3.6/site-packages
ls: cannot access /gpfs/bbp.cscs.ch/apps/hpc/jenkins/deploy/applications/2018-12-19/linux-rhel7-x86_64/gcc-6.4.0/py-libsonata-0.1.0-bauqh4b2nz/lib/python3.6/site-packages: No such file or directory
```

**Comment by jorblancoa** [comment]
Hi @mgeplf,

Do you still have problems with this?
I cannot reproduce the issue...

Cheers,
Jorge

**Comment by mgeplf** [comment]
No, it seems to be working now.

I'm puzzled, though, about what changed.  I see that the file was now created on `Jul 31 05:22`, so it's newer than the one I had, and the contents have certainly changed: the PYTHONPATH for py-libsonata exists.

Before closing this, I'd like to know if this was a change in how the module files are created, or whether the deployment on `Jul 30` didn't finish, and that's why the libsonata directory was missing.

**Comment by matz-e** [comment]
I think that there must have been something going wrong with the installation of `libsonata`. Spack does not have transactions, and if the installation (not the build) of software is faulty, it may be that packages are marked as installed in the database, but files may be missing.

**Comment by mgeplf** [comment]
Ok, that's kind of what I was worried about.

I believe the packages need to be built in place (ie: we can't move them after).  However, the module files can be 'atomically' copied once they are known good, right?

I suppose we'll have to come up with some smoke tests for that sort of thing.  Do you think it would have been a temporary build failure, or something that passed CI but broke the build? The first we could rebuild, the second...I'm not sure what to do.

**Comment by matz-e** [comment]
I think mostly that it's an artifact of temporary build failure. It would be nicer if Spack took better precautions against this happening. IIRC, e.g., Fedora builds in a chroot. That could make installations more atomic (move from chroot into real location), without compromising paths. But then again, it's probably pretty complicated to set up.

I have some thoughts developing about this, but nothing well hashed out so far.

**Comment by mgeplf** [comment]
chroot/fakeroot/(docker?) would be an interesting solution for this.

Whatever the solution, we need something to make sure there is availability: since the module path is being updated on login for people, they assume that loading a module will work.  Transient failures like the one I experienced have to be very rare.  Some sort of atomic deployment of the module files after a smoke test would at least work around build failures.

**Comment by mgeplf** [comment]
Closed in favour of BSD-1
