### ISSUE TITLE
MODULEPATH for PRs should be prepended

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/spack#466]
When dependencies are updated, sourcing the module configuration script of the PR **appends** the new modules to `MODULEPATH`. It would be wiser to have the `MODULEPATH` prepended for new modules.

Changes required to `deploy.lib`. Standard behavior should not be affected.

**Comment by pramodk** [comment]
@matz-e : still relevant?

**Comment by matz-e** [comment]
Not really? Should be in the BSD anyways…
