### ISSUE TITLE
Do we need neuron-serial ?

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/spack#467]
It's more of a general question, but it might solve some issues.

Why do we need neuron-serial ? Is there any use case which can only be run with neuron-serial and not neuron-parallel ? (or is serial in any way faster ?)

Because if we could get rid of this distinction it would at least solve some issues when loading bglibpy it seems ?

**Comment by pramodk** [comment]
yeah...ideally neuron-parallel should be sufficient. We want to try dynamic-mpi library linking. Will take a look at this.

**Comment by pramodk** [comment]
@jorblancoa, also:
* make sure not any recipy is explicitly depending on `neuron~mpi` but `neuron`
* Ioannis's CI plan should be updated so that we don't need to unseat SLURM env variables anymore.

**Comment by wvangeit** [comment]
Move to BSD-5 Jira
