### ISSUE TITLE
Python support/modules needed for Spykfunc

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/spack#48]
The following modules are needed for Spykunc. I can take care of the ones not yet ported:

- [x] bb5
- [x] hdfs
- [x] jprops
- [x] lazy-property
- [x] pyarrow
- [x] progress
- [x] sparkmanager
- [x] spark-bbp

To have CI work faster, and for a smoother installation, it would be good to have the following packages available via spack:

- [ ] python3

**Comment by pramodk** [comment]
I think it make sense to have python installed from source with optimised libraries (e.g. BLAS/MKL) and  necessary python modules. @matz-e and @ferdonline :  could you already make list of which python modules we should have in default python installation? You can check availably python modules with:

```
$ → spack list py
```
